# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trademark', models.CharField(max_length=200)),
                ('car_series', models.CharField(max_length=200)),
                ('original_price', models.CharField(max_length=200)),
                ('current_price', models.CharField(max_length=200)),
                ('car_age', models.CharField(max_length=200)),
                ('car_type', models.CharField(max_length=200)),
                ('seat', models.CharField(max_length=200)),
                ('road_haul', models.CharField(max_length=200)),
                ('gearbox', models.CharField(max_length=200)),
                ('displacement', models.CharField(max_length=200)),
                ('emi_standard', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('collect_num', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPS.Carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=10)),
                ('p_en', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('r_p', models.ManyToManyField(to='APPS.Permission')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=200)),
                ('ticket', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=20)),
                ('sex', models.IntegerField(default=0)),
                ('phone_num', models.CharField(max_length=11)),
                ('user_icon', models.CharField(max_length=200)),
                ('classes', models.CharField(max_length=100)),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='u',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='APPS.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPS.User'),
        ),
        migrations.AddField(
            model_name='car_img',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPS.Carinfo'),
        ),
    ]
